version: "3"
services:
    prisma:
        image: prismagraphql/prisma:1.24
        environment:
            PRISMA_CONFIG: |-
                port: 4466
                databases:
                    default:
                        connector: mysql
                        host: mysql
                        port: 3306
                        user: root
                        password: P@ssw0rd
                        migrations: true
        stdin_open: true
        restart: always
        tty: true
        ports:
            - 4466:4466
    mysql:
        image: mysql:5.7
        environment:
            MYSQL_ROOT_PASSWORD: P@ssw0rd
        stdin_open: true
        tty: true
        volumes:
            - mysql:/var/lib/mysql
volumes:
    mysql:
